# =============================================================================
# import_attendus_v2.py
# =============================================================================
# Remplace import_attendus.py ET import_attendus_disciplinaires.py.
# Importe tous les attendus granulaires (un bullet = un attendu) pour C1, C2, C3.
# type = 'EDD' ou 'disciplinaire'
# Idempotent : INSERT OR IGNORE.
# Prerequis : reinitialiser_attendus_v2.py deja execute.
# =============================================================================

import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent / "activites.db"

# Format : (cycle_code, type_val, domaine, sous_domaine, libelle)

ATTENDUS = [

    # =========================================================================
    # CYCLE 1 — EDD
    # =========================================================================

    ("C1","EDD","Biodiversite et ecosystemes","1.1 - Le tissu vivant de la planete",
     "Formuler des interrogations, a partir de l'observation, pour identifier quelques caracteristiques des etres vivants et prendre conscience de leur diversite et de quelques-unes de leurs interactions."),
    ("C1","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Identifier quelques interactions entre l'etre humain et les autres etres vivants."),
    ("C1","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Prendre conscience de la richesse de la biodiversite dans son environnement proche."),
    ("C1","EDD","Biodiversite et ecosystemes","1.3 - Biodiversite et sante",
     "Formuler des interrogations sur les liens entre le vivant et la sante humaine."),
    ("C1","EDD","Biodiversite et ecosystemes","1.3 - Biodiversite et sante",
     "Prendre conscience d'emotions ressenties au contact de la biodiversite et de leurs bienfaits pour la sante, en particulier en termes de bien-etre."),

    ("C1","EDD","Alimentation",None,
     "Formuler des questions sur les besoins d'une plante."),
    ("C1","EDD","Alimentation",None,
     "Decrire et nommer les differentes saveurs primaires."),
    ("C1","EDD","Alimentation",None,
     "S'interroger sur le gout d'un aliment."),
    ("C1","EDD","Alimentation",None,
     "Prendre conscience que son alimentation a une influence sur sa sante."),
    ("C1","EDD","Alimentation",None,
     "Prendre conscience de l'impact des emballages alimentaires sur la production de dechets."),
    ("C1","EDD","Alimentation",None,
     "Adapter son choix d'aliment en fonction de l'emballage."),
    ("C1","EDD","Alimentation",None,
     "Nommer les principaux criteres de tri des emballages alimentaires."),

    ("C1","EDD","Eau et changement climatique",None,
     "Prendre conscience de la presence de l'eau dans son environnement."),
    ("C1","EDD","Eau et changement climatique",None,
     "Observer et decrire les differents usages de l'eau a l'ecole et a la maison."),
    ("C1","EDD","Eau et changement climatique",None,
     "Formuler des interrogations sur les differents usages quotidiens de l'eau."),
    ("C1","EDD","Eau et changement climatique",None,
     "Adopter quelques ecogestes pour limiter la consommation d'eau a l'ecole."),

    ("C1","EDD","Gestion durable des ressources naturelles",None,
     "Observer et decrire les constructions humaines a l'ecole et dans ses abords, puis nommer et identifier des matieres et des materiaux naturels utilises."),
    ("C1","EDD","Gestion durable des ressources naturelles",None,
     "Prendre conscience des risques lies a l'usage de ressources dans son quotidien."),
    ("C1","EDD","Gestion durable des ressources naturelles",None,
     "Progresser dans la formulation d'interrogations concernant les gestes du quotidien (consommation d'eau et d'energie notamment) pour initier une attitude responsable."),
    ("C1","EDD","Gestion durable des ressources naturelles",None,
     "Adopter quelques ecogestes (extinction des lumieres, utilisation de gourdes, tri des dechets, etc.)."),

    ("C1","EDD","Amenagement durable des territoires",None,
     "Comparer les caracteristiques de son environnement a travers les saisons."),
    ("C1","EDD","Amenagement durable des territoires",None,
     "Identifier differentes constructions humaines et quelques materiaux utilises."),
    ("C1","EDD","Amenagement durable des territoires",None,
     "Prendre conscience de la diversite des constructions dans son environnement."),
    ("C1","EDD","Amenagement durable des territoires",None,
     "Prendre conscience des risques qui concernent son environnement (risques naturels, risques technologiques, etc.)."),

    ("C1","EDD","Numerique",None,
     "Prendre conscience des usages multiples des ecrans et des risques associes pour identifier des gestes favorables a sa sante."),
    ("C1","EDD","Numerique",None,
     "Prendre conscience que le numerique repose sur des objets qui ont une duree de vie limitee et peuvent donc etre repares, tries, recycles, avant d'etre remplaces."),

    # =========================================================================
    # CYCLE 1 — DISCIPLINAIRES
    # =========================================================================

    # Domaine 1 - Langage oral
    ("C1","disciplinaire","Mobiliser le langage","Oral",
     "Communiquer avec les adultes et avec les autres enfants par le langage, en se faisant comprendre."),
    ("C1","disciplinaire","Mobiliser le langage","Oral",
     "S'exprimer dans un langage oral syntaxiquement correct et precis."),
    ("C1","disciplinaire","Mobiliser le langage","Oral",
     "Utiliser le lexique appris en classe de facon appropriee."),
    ("C1","disciplinaire","Mobiliser le langage","Oral",
     "Reformuler son propos pour se faire mieux comprendre."),
    ("C1","disciplinaire","Mobiliser le langage","Oral",
     "Reformuler le propos d'autrui."),
    ("C1","disciplinaire","Mobiliser le langage","Oral",
     "Pratiquer divers usages de la langue orale : raconter, decrire, evoquer, expliquer, questionner, proposer des solutions, discuter un point de vue."),
    ("C1","disciplinaire","Mobiliser le langage","Oral",
     "Dire de memoire et de maniere expressive plusieurs comptines et poesies."),
    # Ecrit
    ("C1","disciplinaire","Mobiliser le langage","Decouverte de l'ecrit",
     "Comprendre des textes ecrits sans autre aide que le langage entendu."),
    ("C1","disciplinaire","Mobiliser le langage","Decouverte de l'ecrit",
     "Manifester de la curiosite par rapport a la comprehension et a la production de l'ecrit."),
    ("C1","disciplinaire","Mobiliser le langage","Decouverte de l'ecrit",
     "Pouvoir redire les mots d'une phrase ecrite apres sa lecture par l'adulte, les mots du titre connu d'un livre ou d'un texte."),
    ("C1","disciplinaire","Mobiliser le langage","Decouverte de l'ecrit",
     "Participer verbalement a la production d'un ecrit. Savoir qu'on n'ecrit pas comme on parle."),
    # Phonologie
    ("C1","disciplinaire","Mobiliser le langage","Phonologie",
     "Reperer des regularites dans la langue a l'oral en francais (eventuellement dans une autre langue)."),
    ("C1","disciplinaire","Mobiliser le langage","Phonologie",
     "Distinguer et manipuler des syllabes : scander les syllabes constitutives d'un mot, comprendre qu'on peut en supprimer, en ajouter, en inverser."),
    ("C1","disciplinaire","Mobiliser le langage","Phonologie",
     "Reperer et produire des rimes, des assonances."),
    ("C1","disciplinaire","Mobiliser le langage","Phonologie",
     "Identifier et distinguer a l'oreille des sons dans des mots ou des syllabes : les sons-voyelles (a, i, o, u...) et quelques sons-consonnes parmi les plus faciles a percevoir (f, s, l, r, m, n...)."),
    # Alphabet et ecriture
    ("C1","disciplinaire","Mobiliser le langage","Alphabet et ecriture",
     "Reconnaitre les lettres de l'alphabet, connaitre leur nom, savoir que le nom d'une lettre peut etre different du son qu'elle transcrit."),
    ("C1","disciplinaire","Mobiliser le langage","Alphabet et ecriture",
     "Connaitre les correspondances entre les trois manieres d'ecrire les lettres : cursive, script, capitales d'imprimerie, et commencer a faire le lien avec le son qu'elles codent. Copier a l'aide d'un clavier."),
    ("C1","disciplinaire","Mobiliser le langage","Alphabet et ecriture",
     "Reconnaitre son prenom ecrit en lettres capitales, en script ou en cursive. Connaitre le nom des lettres qui le composent."),
    ("C1","disciplinaire","Mobiliser le langage","Alphabet et ecriture",
     "Copier en cursive un mot ou une tres courte phrase dont le sens est connu."),
    ("C1","disciplinaire","Mobiliser le langage","Alphabet et ecriture",
     "Ecrire son prenom en ecriture cursive, sans modele."),
    ("C1","disciplinaire","Mobiliser le langage","Alphabet et ecriture",
     "Ecrire seul un mot en utilisant des lettres ou groupes de lettres empruntes aux mots connus."),

    # Domaine 2 - Activite physique
    ("C1","disciplinaire","Activite physique",None,
     "Courir, sauter, lancer de differentes facons, dans des espaces et avec des materiels varies, dans un but precis."),
    ("C1","disciplinaire","Activite physique",None,
     "Ajuster et enchainer ses actions et ses deplacements en fonction d'obstacles a franchir ou de la trajectoire d'objets sur lesquels agir."),
    ("C1","disciplinaire","Activite physique",None,
     "Se deplacer avec aisance et en securite dans des environnements varies, naturels ou amenages."),
    ("C1","disciplinaire","Activite physique",None,
     "Construire et conserver une sequence d'actions et de deplacements, en relation avec d'autres partenaires, avec ou sans support musical."),
    ("C1","disciplinaire","Activite physique",None,
     "Coordonner ses gestes et ses deplacements avec ceux des autres, lors de rondes et jeux chantes."),
    ("C1","disciplinaire","Activite physique",None,
     "Cooperer, exercer des roles differents complementaires, s'opposer, elaborer des strategies pour viser un but ou un effet commun."),

    # Domaine 3 - Activites artistiques
    ("C1","disciplinaire","Activites artistiques","Arts plastiques",
     "Choisir differents outils, mediums, supports en fonction d'un projet ou d'une consigne et les utiliser en adaptant son geste."),
    ("C1","disciplinaire","Activites artistiques","Arts plastiques",
     "Pratiquer le dessin pour representer ou illustrer, en etant fidele au reel ou a un modele, ou en inventant."),
    ("C1","disciplinaire","Activites artistiques","Arts plastiques",
     "Realiser une composition personnelle en reproduisant des graphismes. Creer des graphismes nouveaux."),
    ("C1","disciplinaire","Activites artistiques","Arts plastiques",
     "Realiser des compositions plastiques, seul ou en petit groupe, en choisissant et combinant des materiaux, en reinvestissant des techniques et des procedes."),
    ("C1","disciplinaire","Activites artistiques","Musique",
     "Avoir memorise un repertoire varie de comptines et de chansons et les interpreter de maniere expressive."),
    ("C1","disciplinaire","Activites artistiques","Musique",
     "Jouer avec sa voix pour explorer des variantes de timbre, d'intensite, de hauteur, de nuance."),
    ("C1","disciplinaire","Activites artistiques","Musique",
     "Reperer et reproduire, corporellement ou avec des instruments, des formules rythmiques simples."),
    ("C1","disciplinaire","Activites artistiques","Expression",
     "Decrire une image, parler d'un extrait musical et exprimer son ressenti ou sa comprehension en utilisant un vocabulaire adapte."),
    ("C1","disciplinaire","Activites artistiques","Expression",
     "Proposer des solutions dans des situations de projet, de creation, de resolution de problemes, avec son corps, sa voix ou des objets sonores."),

    # Domaine 4 - Mathematiques
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Comparer deux collections d'objets pour savoir laquelle en contient le plus, en utilisant differentes methodes : le coup d'oeil, la mise en correspondance un a un, ou le comptage."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Realiser une collection dont le cardinal (nombre) est compris entre 1 et 10."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Utiliser le denombrement pour comparer deux quantites ou pour realiser une collection de quantite egale a la collection proposee (quantites inferieures ou egales a 10)."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Utiliser le nombre pour exprimer la position d'un objet ou d'une personne dans un jeu, dans une situation organisee, sur un rang ou pour comparer des positions."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Mobiliser des symboles analogiques (constellations, doigts), verbaux (mots-nombres) ou ecrits (en chiffres), pour communiquer des informations sur une quantite, jusqu'a 10 au moins."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Avoir compris que le cardinal ne change pas si on modifie la disposition spatiale ou la nature des elements."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Avoir compris que tout nombre s'obtient en ajoutant un au nombre precedent et que cela correspond a l'ajout d'une unite a la quantite precedente."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Quantifier des collections jusqu'a dix au moins ; les composer et les decomposer par manipulations effectives puis mentales."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Dire combien il faut ajouter ou enlever pour obtenir des quantites ne depassant pas dix."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Parler des nombres a l'aide de leur decomposition."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Dire la suite des nombres jusqu'a trente. Dire la suite des nombres a partir d'un nombre donne (entre 1 et 30)."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Lire les nombres ecrits en chiffres jusqu'a 10."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Commencer a ecrire les nombres en chiffres jusqu'a 10."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Commencer a comparer deux nombres inferieurs ou egaux a 10 ecrits en chiffres."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Commencer a positionner des nombres les uns par rapport aux autres et a completer une bande numerique lacunaire (les nombres en jeu sont inferieurs ou egaux a 10)."),
    ("C1","disciplinaire","Mathematiques","Nombres",
     "Commencer a resoudre des problemes de composition de deux collections, d'ajout ou de retrait, de produit ou de partage (les nombres en jeu sont tous inferieurs ou egaux a 10)."),
    ("C1","disciplinaire","Mathematiques","Geometrie",
     "Classer des objets en fonction de caracteristiques liees a leur forme."),
    ("C1","disciplinaire","Mathematiques","Geometrie",
     "Reconnaitre quelques solides (cube, pyramide, boule, cylindre)."),
    ("C1","disciplinaire","Mathematiques","Geometrie",
     "Savoir nommer quelques formes planes (carre, triangle, cercle ou disque, rectangle) et ce dans toutes leurs orientations et configurations."),
    ("C1","disciplinaire","Mathematiques","Geometrie",
     "Classer ou ranger des objets selon un critere de longueur ou de masse ou de contenance."),
    ("C1","disciplinaire","Mathematiques","Geometrie",
     "Reproduire un assemblage a partir d'un modele (puzzle, pavage, assemblage de solides)."),
    ("C1","disciplinaire","Mathematiques","Geometrie",
     "Reproduire, dessiner des formes planes."),
    ("C1","disciplinaire","Mathematiques","Geometrie",
     "Identifier une organisation reguliere (repetition) et poursuivre son application."),

    # Domaine 5 - Explorer le monde
    ("C1","disciplinaire","Explorer le monde","Temps",
     "Situer des evenements vecus les uns par rapport aux autres et en les reperant dans la journee, la semaine, le mois ou une saison."),
    ("C1","disciplinaire","Explorer le monde","Temps",
     "Ordonner une suite de photographies ou d'images, pour rendre compte d'une situation vecue ou d'un recit fictif entendu, en marquant de maniere exacte succession et simultaneite."),
    ("C1","disciplinaire","Explorer le monde","Temps",
     "Utiliser des marqueurs temporels adaptes (puis, pendant, avant, apres...) dans des recits, descriptions ou explications."),
    ("C1","disciplinaire","Explorer le monde","Espace",
     "Situer des objets par rapport a soi, entre eux, par rapport a des objets reperes."),
    ("C1","disciplinaire","Explorer le monde","Espace",
     "Se situer par rapport a d'autres, par rapport a des objets reperes."),
    ("C1","disciplinaire","Explorer le monde","Espace",
     "Dans un environnement bien connu, realiser un trajet, un parcours a partir de sa representation (dessin ou codage)."),
    ("C1","disciplinaire","Explorer le monde","Espace",
     "Elaborer des premiers essais de representation plane, communicables (construction d'un code commun)."),
    ("C1","disciplinaire","Explorer le monde","Espace",
     "Orienter et utiliser correctement une feuille de papier, un livre ou un autre support d'ecrit, en fonction de consignes, d'un but ou d'un projet precis."),
    ("C1","disciplinaire","Explorer le monde","Espace",
     "Utiliser des marqueurs spatiaux adaptes (devant, derriere, droite, gauche, dessus, dessous, etc.) dans des recits, descriptions ou explications."),
    ("C1","disciplinaire","Explorer le monde","Vivant",
     "Reconnaitre et decrire les principales etapes du developpement d'un animal ou d'un vegetal, dans une situation d'observation du reel ou sur des images fixes ou animees."),
    ("C1","disciplinaire","Explorer le monde","Vivant",
     "Connaitre les besoins essentiels de quelques animaux et vegetaux."),
    ("C1","disciplinaire","Explorer le monde","Corps et sante",
     "Situer et nommer les differentes parties du corps humain, sur soi ou sur une representation."),
    ("C1","disciplinaire","Explorer le monde","Corps et sante",
     "Connaitre et mettre en oeuvre quelques regles d'hygiene corporelle et d'une vie saine."),
    ("C1","disciplinaire","Explorer le monde","Objets et materiaux",
     "Choisir, utiliser et savoir designer des outils et des materiaux adaptes a une situation, a des actions techniques specifiques (plier, couper, coller, assembler, actionner...)."),
    ("C1","disciplinaire","Explorer le monde","Objets et materiaux",
     "Realiser des constructions ; construire des maquettes simples en fonction de plans ou d'instructions de montage."),
    ("C1","disciplinaire","Explorer le monde","Numerique",
     "Utiliser des objets numeriques : appareil photo, tablette, ordinateur."),
    ("C1","disciplinaire","Explorer le monde","Securite",
     "Prendre en compte les risques de l'environnement familier proche (objets et comportements dangereux, produits toxiques)."),
    ("C1","disciplinaire","Explorer le monde","Securite",
     "Commencer a adopter une attitude responsable en matiere de respect des lieux et de protection du vivant."),

    # =========================================================================
    # CYCLE 2 — EDD
    # =========================================================================

    ("C2","EDD","Biodiversite et ecosystemes","1.1 - Le tissu vivant de la planete",
     "Etre sensible aux incidences de son comportement sur la biodiversite."),
    ("C2","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Decrire quelques interactions entre l'humain et les autres etres vivants pour expliquer differents impacts des actions humaines sur la biodiversite."),
    ("C2","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Apprehender la biodiversite comme bien commun et etre sensible aux incidences de son comportement sur la biodiversite."),
    ("C2","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Proposer des actions simples favorables a la preservation de la biodiversite en expliquant leur interet."),
    ("C2","EDD","Biodiversite et ecosystemes","1.3 - Biodiversite et sante",
     "Etre sensible aux incidences de son comportement sur son environnement et sa sante."),
    ("C2","EDD","Biodiversite et ecosystemes","1.3 - Biodiversite et sante",
     "Mettre en oeuvre et comprendre le sens de quelques ecogestes favorables a la biodiversite visant une meilleure sante des humains et des autres etres vivants."),

    ("C2","EDD","Alimentation",None,
     "Comparer des modes de production agricole et les impacts sur l'ecosysteme : taille de l'exploitation, engins et intrants agricoles, techniques utilisees."),
    ("C2","EDD","Alimentation",None,
     "Representer les relations alimentaires entre les organismes vivants, notamment en lien avec la production agricole."),
    ("C2","EDD","Alimentation",None,
     "Pratiquer une demarche d'investigation visant a definir le regime alimentaire d'animaux."),
    ("C2","EDD","Alimentation",None,
     "Pratiquer une demarche d'investigation visant a definir ce qu'est un equilibre alimentaire."),
    ("C2","EDD","Alimentation",None,
     "Identifier les fruits et legumes de saison."),
    ("C2","EDD","Alimentation",None,
     "Expliquer l'interet de consommer des aliments de saison et issus de circuits courts et de proximite."),
    ("C2","EDD","Alimentation",None,
     "Expliquer l'importance et les moyens de reduire les dechets lies a la consommation alimentaire."),

    ("C2","EDD","Eau et changement climatique",None,
     "Identifier et nommer differents reservoirs d'eau de son environnement (lac, riviere, ruisseau, glacier, etc.)."),
    ("C2","EDD","Eau et changement climatique",None,
     "Decrire differents usages de l'eau au quotidien et mesurer son importance en tant que bien commun."),
    ("C2","EDD","Eau et changement climatique",None,
     "Expliquer les incidences de son comportement sur la qualite et sur la disponibilite de l'eau."),
    ("C2","EDD","Eau et changement climatique",None,
     "Imaginer des solutions pour reduire le gaspillage de l'eau a la maison."),
    ("C2","EDD","Eau et changement climatique",None,
     "Participer a une action concrete de gestion raisonnee de l'eau a l'ecole."),

    ("C2","EDD","Gestion durable des ressources naturelles",None,
     "Etre sensibilise aux incidences de ses consommations, par exemple consommation de papier, alimentation."),
    ("C2","EDD","Gestion durable des ressources naturelles",None,
     "Identifier des liens entre l'alimentation, les besoins des etres humains et la gestion des ressources."),
    ("C2","EDD","Gestion durable des ressources naturelles",None,
     "Avoir conscience de l'impact des actions individuelles sur la reduction des dechets."),
    ("C2","EDD","Gestion durable des ressources naturelles",None,
     "Imaginer des solutions et mettre en oeuvre une action concrete pour reduire le gaspillage alimentaire, le gaspillage de papier, etc."),
    ("C2","EDD","Gestion durable des ressources naturelles",None,
     "Comprendre le sens et l'interet de quelques ecogestes a appliquer a l'ecole concernant la gestion des dechets."),

    ("C2","EDD","Amenagement durable des territoires",None,
     "Identifier et nommer quelques amenagements de son environnement immediat, de sa commune, en lien avec le developpement durable."),
    ("C2","EDD","Amenagement durable des territoires",None,
     "Participer a une action d'amenagement durable proposee dans sa commune."),
    ("C2","EDD","Amenagement durable des territoires",None,
     "Identifier les equipements et amenagements qui permettent de mieux s'adapter aux evenements climatiques extremes (pluie intense, canicule, etc.)."),
    ("C2","EDD","Amenagement durable des territoires",None,
     "Comparer des paysages, des images de sa commune du passe et du present en faisant ressortir des evolutions en lien avec un ou des risques."),
    ("C2","EDD","Amenagement durable des territoires",None,
     "Etre sensibilise aux incidences du choix de son mode de deplacement sur sa sante."),

    ("C2","EDD","Numerique",None,
     "Pratiquer une premiere demarche d'investigation sur une question liee a un enjeu de developpement durable, et se rendre compte de l'interet des outils numeriques."),
    ("C2","EDD","Numerique",None,
     "Etre sensibilise a l'impact du numerique sur l'environnement (utilisation de composants, d'electricite)."),
    ("C2","EDD","Numerique",None,
     "Comprendre le sens et l'interet d'adopter quelques ecogestes concernant les usages du numerique (reparer, recycler) et les mettre en oeuvre."),

    # =========================================================================
    # CYCLE 2 — DISCIPLINAIRES
    # =========================================================================

    ("C2","disciplinaire","Francais","Langage oral",
     "Conserver une attention soutenue lors de situations d'ecoute ou d'echanges et manifester, si besoin et a bon escient, son incomprehension."),
    ("C2","disciplinaire","Francais","Langage oral",
     "Dans les differentes situations de communication, produire des enonces clairs en tenant compte de l'objet du propos et des interlocuteurs."),
    ("C2","disciplinaire","Francais","Langage oral",
     "Pratiquer les formes de discours attendues -- notamment raconter, decrire, expliquer -- dans des situations ou les attentes sont explicites ; en particulier raconter seul un recit etudie en classe."),
    ("C2","disciplinaire","Francais","Langage oral",
     "Participer avec pertinence a un echange (questionner, repondre a une interpellation, exprimer un accord ou un desaccord, apporter un complement, etc.)."),

    ("C2","disciplinaire","Francais","Lecture",
     "Identifier des mots rapidement : decoder aisement des mots inconnus reguliers, reconnaitre des mots frequents et des mots irreguliers memorises."),
    ("C2","disciplinaire","Francais","Lecture",
     "Lire et comprendre des textes varies, adaptes a la maturite et a la culture scolaire des eleves."),
    ("C2","disciplinaire","Francais","Lecture",
     "Lire a voix haute avec fluidite, apres preparation, un texte d'une demi-page (1 400 a 1 500 signes) ; participer a une lecture dialoguee apres preparation."),

    ("C2","disciplinaire","Francais","Ecriture",
     "Copier ou transcrire, dans une ecriture lisible, un texte d'une dizaine de lignes en respectant la mise en page, la ponctuation, l'orthographe et en soignant la presentation."),
    ("C2","disciplinaire","Francais","Ecriture",
     "Rediger un texte d'environ une demi-page, coherent, organise, ponctue, pertinent par rapport a la visee et au destinataire."),
    ("C2","disciplinaire","Francais","Ecriture",
     "Ameliorer un texte, notamment son orthographe, en tenant compte d'indications."),

    ("C2","disciplinaire","Francais","Etude de la langue",
     "Orthographier les mots les plus frequents (notamment en situation scolaire) et les mots invariables memorises."),
    ("C2","disciplinaire","Francais","Etude de la langue",
     "Raisonner pour realiser les accords dans le groupe nominal d'une part (determinant, nom, adjectif), entre le verbe et son sujet d'autre part (cas simples)."),
    ("C2","disciplinaire","Francais","Etude de la langue",
     "Utiliser ses connaissances sur la langue pour mieux s'exprimer a l'oral, pour mieux comprendre des mots et des textes, pour ameliorer des textes ecrits."),

    ("C2","disciplinaire","Arts plastiques",None,
     "Realiser et donner a voir, individuellement ou collectivement, des productions plastiques de natures diverses."),
    ("C2","disciplinaire","Arts plastiques",None,
     "Proposer des reponses inventives dans un projet individuel ou collectif."),
    ("C2","disciplinaire","Arts plastiques",None,
     "Cooperer dans un projet artistique."),
    ("C2","disciplinaire","Arts plastiques",None,
     "S'exprimer sur sa production, celle de ses pairs, sur l'art."),
    ("C2","disciplinaire","Arts plastiques",None,
     "Comparer quelques oeuvres d'art."),

    ("C2","disciplinaire","Education musicale",None,
     "Experimenter sa voix parlee et chantee, explorer ses parametres, la mobiliser au benefice d'une reproduction expressive."),
    ("C2","disciplinaire","Education musicale",None,
     "Connaitre et mettre en oeuvre les conditions d'une ecoute attentive et precise."),
    ("C2","disciplinaire","Education musicale",None,
     "Imaginer des organisations simples ; creer des sons et maitriser leur succession."),
    ("C2","disciplinaire","Education musicale",None,
     "Exprimer sa sensibilite et exercer son esprit critique tout en respectant les gouts et points de vue de chacun."),

    ("C2","disciplinaire","EPS","Performance",
     "Courir, sauter, lancer a des intensites et des durees variables dans des contextes adaptes."),
    ("C2","disciplinaire","EPS","Performance",
     "Savoir differencier : courir vite et courir longtemps / lancer loin et lancer precis / sauter haut et sauter loin."),
    ("C2","disciplinaire","EPS","Performance",
     "Accepter de viser une performance mesuree et de se confronter aux autres."),
    ("C2","disciplinaire","EPS","Performance",
     "Remplir quelques roles specifiques."),
    ("C2","disciplinaire","EPS","Environnements varies",
     "Realiser un parcours en adaptant ses deplacements a un environnement inhabituel. L'espace est amenage et securise."),
    ("C2","disciplinaire","EPS","Environnements varies",
     "Respecter les regles de securite qui s'appliquent."),
    ("C2","disciplinaire","EPS","Expression artistique",
     "Mobiliser le pouvoir expressif du corps, en reproduisant une sequence simple d'actions apprise ou en presentant une action inventee."),
    ("C2","disciplinaire","EPS","Expression artistique",
     "S'adapter au rythme, memoriser des pas, des figures, des elements et des enchainements pour realiser des actions individuelles et collectives."),
    ("C2","disciplinaire","EPS","Affrontement",
     "S'engager dans un affrontement individuel ou collectif en respectant les regles du jeu."),
    ("C2","disciplinaire","EPS","Affrontement",
     "Controler son engagement moteur et affectif pour reussir des actions simples."),
    ("C2","disciplinaire","EPS","Affrontement",
     "Connaitre le but du jeu."),
    ("C2","disciplinaire","EPS","Affrontement",
     "Reconnaitre ses partenaires et ses adversaires."),

    ("C2","disciplinaire","EMC","Respecter autrui",
     "Respecter autrui : accepter et respecter les differences ; respecter les engagements pris envers soi-meme et envers les autres ; adopter un comportement responsable par rapport a soi et a autrui ; savoir ecouter autrui."),
    ("C2","disciplinaire","EMC","Respecter autrui",
     "Identifier et partager des emotions, des sentiments dans des situations et a propos d'objets diversifies."),
    ("C2","disciplinaire","EMC","Valeurs de la Republique",
     "Respecter les regles de la vie collective."),
    ("C2","disciplinaire","EMC","Valeurs de la Republique",
     "Connaitre les valeurs, les principes et les symboles de la Republique francaise : le drapeau, l'hymne national, les monuments, la fete nationale."),
    ("C2","disciplinaire","EMC","Valeurs de la Republique",
     "Acceder a une premiere connaissance des cadres d'une societe democratique."),
    ("C2","disciplinaire","EMC","Culture civique",
     "Participer et prendre sa place dans un groupe."),
    ("C2","disciplinaire","EMC","Culture civique",
     "Distinguer son interet personnel de l'interet general."),
    ("C2","disciplinaire","EMC","Culture civique",
     "Ecouter autrui et produire un point de vue argumente."),

    ("C2","disciplinaire","Questionner le monde","Matiere",
     "Identifier les trois etats de la matiere et observer des changements d'etats."),
    ("C2","disciplinaire","Questionner le monde","Matiere",
     "Identifier un changement d'etat de l'eau dans un phenomene de la vie quotidienne."),
    ("C2","disciplinaire","Questionner le monde","Vivant",
     "Connaitre des caracteristiques du monde vivant, ses interactions, sa diversite."),
    ("C2","disciplinaire","Questionner le monde","Vivant",
     "Reconnaitre des comportements favorables a sa sante."),
    ("C2","disciplinaire","Questionner le monde","Objets techniques",
     "Comprendre la fonction et le fonctionnement d'objets fabriques."),
    ("C2","disciplinaire","Questionner le monde","Objets techniques",
     "Realiser quelques objets et circuits electriques simples, en respectant des regles elementaires de securite."),
    ("C2","disciplinaire","Questionner le monde","Objets techniques",
     "Commencer a s'approprier un environnement numerique."),
    ("C2","disciplinaire","Questionner le monde","Espace",
     "Se reperer dans l'espace et le representer."),
    ("C2","disciplinaire","Questionner le monde","Espace",
     "Situer un lieu sur une carte, sur un globe ou sur un ecran informatique."),
    ("C2","disciplinaire","Questionner le monde","Temps",
     "Se reperer dans le temps et mesurer des durees."),
    ("C2","disciplinaire","Questionner le monde","Temps",
     "Reperer et situer quelques evenements dans un temps long."),
    ("C2","disciplinaire","Questionner le monde","Organisations du monde",
     "Comparer quelques modes de vie des hommes et des femmes, et quelques representations du monde."),
    ("C2","disciplinaire","Questionner le monde","Organisations du monde",
     "Identifier quelques interactions elementaires entre mode de vie et environnement."),
    ("C2","disciplinaire","Questionner le monde","Organisations du monde",
     "Comprendre qu'un espace est organise."),
    ("C2","disciplinaire","Questionner le monde","Organisations du monde",
     "Identifier des paysages."),

    ("C2","disciplinaire","Mathematiques","Nombres et calculs",
     "Comprendre et utiliser des nombres entiers pour denombrrer, ordonner, reperer, comparer."),
    ("C2","disciplinaire","Mathematiques","Nombres et calculs",
     "Nommer, lire, ecrire, representer des nombres entiers."),
    ("C2","disciplinaire","Mathematiques","Nombres et calculs",
     "Resoudre des problemes en utilisant des nombres entiers et le calcul."),
    ("C2","disciplinaire","Mathematiques","Nombres et calculs",
     "Calculer avec des nombres entiers."),
    ("C2","disciplinaire","Mathematiques","Grandeurs et mesures",
     "Comparer, estimer, mesurer des longueurs, des masses, des contenances, des durees."),
    ("C2","disciplinaire","Mathematiques","Grandeurs et mesures",
     "Utiliser le lexique, les unites, les instruments de mesures specifiques de ces grandeurs."),
    ("C2","disciplinaire","Mathematiques","Grandeurs et mesures",
     "Resoudre des problemes impliquant des longueurs, des masses, des contenances, des durees, des prix."),
    ("C2","disciplinaire","Mathematiques","Espace et geometrie",
     "Se situer dans l'espace et decrire sa position ou celle d'un objet en utilisant des mots precis (devant, derriere, a gauche, a droite, etc.) ; suivre ou donner un itineraire simple en s'appuyant sur un plan ou un quadrillage."),
    ("C2","disciplinaire","Mathematiques","Espace et geometrie",
     "Reconnaitre, nommer, decrire, reproduire quelques solides."),
    ("C2","disciplinaire","Mathematiques","Espace et geometrie",
     "Reconnaitre, nommer, decrire, reproduire, construire quelques figures geometriques."),
    ("C2","disciplinaire","Mathematiques","Espace et geometrie",
     "Reconnaitre et utiliser les notions d'alignement, d'angle droit, d'egalite de longueurs, de milieu, de symetrie."),

    # =========================================================================
    # CYCLE 3 — EDD
    # =========================================================================

    ("C3","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Identifier differents enjeux lies a la preservation de la biodiversite a l'echelle d'un territoire et des acteurs associes."),
    ("C3","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Participer a une action concrete collective ou individuelle de preservation de la biodiversite et envisager des actions qui depassent le cadre de l'ecole ou de l'etablissement."),
    ("C3","EDD","Biodiversite et ecosystemes","1.2 - Erosion, gestion et preservation",
     "Apprehender la biodiversite comme un bien commun."),
    ("C3","EDD","Biodiversite et ecosystemes","1.3 - Biodiversite et sante",
     "Distinguer une connaissance scientifique d'une opinion sur les comportements favorables a la sante humaine."),
    ("C3","EDD","Biodiversite et ecosystemes","1.3 - Biodiversite et sante",
     "Identifier les valeurs qui peuvent etre attribuees a la nature et a la sante des humains, des animaux et des ecosystemes."),
    ("C3","EDD","Biodiversite et ecosystemes","1.3 - Biodiversite et sante",
     "Faire un lien entre la consommation de produits locaux, de saison et issus d'une agriculture durable avec la sante des humains, des animaux et des ecosystemes."),

    ("C3","EDD","Alimentation",None,
     "Reperer les acteurs et les specificites geographiques des productions agricoles."),
    ("C3","EDD","Alimentation",None,
     "Relier la production alimentaire a quelques objectifs de developpement durable (par exemple, les objectifs 13 et 15)."),
    ("C3","EDD","Alimentation",None,
     "Distinguer ce qui releve de la connaissance scientifique, de la croyance ou de la simple opinion en matiere d'alimentation et de sante."),
    ("C3","EDD","Alimentation",None,
     "Proposer une solution concrete a l'echelle de l'ecole ou du college pour reduire le gaspillage alimentaire."),
    ("C3","EDD","Alimentation",None,
     "Envisager des actions a l'echelle de la commune en lien avec les acteurs impliques dans la lutte contre le gaspillage alimentaire."),
    ("C3","EDD","Alimentation",None,
     "Identifier et justifier les ecogestes pour une consommation alimentaire responsable (reduction des dechets, lutte contre le gaspillage, reduction des emissions de gaz a effet de serre, prise en compte du bien-etre animal, etc.)."),

    ("C3","EDD","Eau et changement climatique","3.1 - Le cycle de l'eau",
     "Representer le cycle de l'eau et expliquer son fonctionnement systemique."),
    ("C3","EDD","Eau et changement climatique","3.1 - Le cycle de l'eau",
     "Reperer des differences de climat et les mettre en lien avec le cycle de l'eau."),
    ("C3","EDD","Eau et changement climatique","3.2 - Les usages de l'eau",
     "Relier le cycle de l'eau avec les usages de l'eau par les societes humaines."),
    ("C3","EDD","Eau et changement climatique","3.2 - Les usages de l'eau",
     "Reperer des ecarts, a l'echelle mondiale, entre la disponibilite de l'eau et ses usages."),
    ("C3","EDD","Eau et changement climatique","3.2 - Les usages de l'eau",
     "Reperer et identifier des acteurs locaux impliques dans la gestion de la ressource en eau dans son environnement proche."),
    ("C3","EDD","Eau et changement climatique","3.2 - Les usages de l'eau",
     "Pratiquer une demarche d'investigation en lien avec la disponibilite ou la qualite des eaux locales."),
    ("C3","EDD","Eau et changement climatique","3.2 - Les usages de l'eau",
     "Reperer des conflits d'usages de l'eau et identifier les valeurs mises en jeu (solidarite, equite, justice)."),
    ("C3","EDD","Eau et changement climatique","3.2 - Les usages de l'eau",
     "Identifier l'eau comme un bien commun a preserver."),
    ("C3","EDD","Eau et changement climatique","3.3 - Gestion durable de l'eau",
     "Identifier des valeurs mises en jeu (solidarite, equite, justice) dans les questions de gestion et de partage de l'eau."),
    ("C3","EDD","Eau et changement climatique","3.3 - Gestion durable de l'eau",
     "Proposer des actions pour sensibiliser la population locale aux enjeux de l'eau en tant que bien commun, a preserver et a partager."),
    ("C3","EDD","Eau et changement climatique","3.3 - Gestion durable de l'eau",
     "Proposer des actions pour limiter les impacts des activites humaines sur l'eau qui depassent le cadre de l'ecole."),

    ("C3","EDD","Gestion durable des ressources naturelles",None,
     "Pratiquer une demarche d'investigation pour comprendre les benefices d'une gestion raisonnee de ces ressources."),
    ("C3","EDD","Gestion durable des ressources naturelles",None,
     "Reperer des complementarites et des mises en tension possibles entre des enjeux ethiques, environnementaux et sociaux lies a l'usage des ressources."),
    ("C3","EDD","Gestion durable des ressources naturelles",None,
     "Identifier et justifier des ecogestes en lien avec l'usage des ressources."),
    ("C3","EDD","Gestion durable des ressources naturelles",None,
     "Participer a une action collective concrete pour une consommation raisonnee et un partage ethique des ressources."),

    ("C3","EDD","Amenagement durable des territoires",None,
     "Identifier le role de l'urbanisation dans le changement climatique (chauffage, transports, artificialisation des sols) et dans la pollution de l'air."),
    ("C3","EDD","Amenagement durable des territoires",None,
     "Identifier, en milieu urbain, les actions qui peuvent etre mises en place face au changement climatique (strategies d'attenuation et d'adaptation) d'une part, et pour reduire la pollution de l'air d'autre part."),
    ("C3","EDD","Amenagement durable des territoires",None,
     "Relier la question de l'habiter en ville a differents objectifs de developpement durable."),
    ("C3","EDD","Amenagement durable des territoires",None,
     "Representer des possibles pour la ville de demain par la realisation de maquettes, schemas ou dessins."),
    ("C3","EDD","Amenagement durable des territoires",None,
     "Expliquer la vulnerabilite des littoraux en lien avec le changement climatique."),
    ("C3","EDD","Amenagement durable des territoires",None,
     "Participer a une action concrete de transformation ou preservation de son environnement proche pour reduire les risques."),
    ("C3","EDD","Amenagement durable des territoires",None,
     "Differencier des choix possibles de moyens de deplacement en fonction de leur impact sur la sante et sur l'environnement."),
    ("C3","EDD","Amenagement durable des territoires",None,
     "Identifier et justifier le choix d'un moyen de transport durable dans une situation donnee."),

    ("C3","EDD","Numerique",None,
     "Participer a un diagnostic de son lieu de vie avec des outils numeriques, en caracteriser les specificites au regard des ODD et ainsi reperer les principaux enjeux de transition ecologique."),
    ("C3","EDD","Numerique",None,
     "Estimer son empreinte carbone en utilisant un outil de simulation en ligne dans une perspective d'education au choix."),
    ("C3","EDD","Numerique",None,
     "Pratiquer une demarche d'investigation sur un enjeu de developpement durable en s'appuyant sur Internet, distinguer les connaissances des opinions et justifier son point de vue a l'aide des informations collectees."),
    ("C3","EDD","Numerique",None,
     "Identifier des enjeux de citoyennete et de sante lies aux usages du numerique."),
    ("C3","EDD","Numerique",None,
     "Pratiquer une demarche d'investigation pour estimer l'empreinte carbone de quelques objets numeriques en utilisant des simulateurs et convertisseurs numeriques fiables."),
    ("C3","EDD","Numerique",None,
     "Reperer des outils numeriques de simulation pouvant servir d'aide a la decision en termes de comportements ecoresponsables, afin de reduire les incidences environnementales de ses gestes."),
    ("C3","EDD","Numerique",None,
     "Envisager des actions et s'engager dans le cadre d'un evenement visant a promouvoir des usages du numerique ecoresponsables et citoyens."),

    # =========================================================================
    # CYCLE 3 — DISCIPLINAIRES
    # =========================================================================

    ("C3","disciplinaire","Francais","Langage oral",
     "Ecouter un recit et manifester sa comprehension en repondant a des questions sans se reporter au texte."),
    ("C3","disciplinaire","Francais","Langage oral",
     "Dire de memoire un texte a haute voix."),
    ("C3","disciplinaire","Francais","Langage oral",
     "Realiser une courte presentation orale en prenant appui sur des notes ou sur diaporama ou autre outil (numerique par exemple)."),
    ("C3","disciplinaire","Francais","Langage oral",
     "Participer de facon constructive aux echanges avec d'autres eleves dans un groupe pour confronter des reactions ou des points de vue."),

    ("C3","disciplinaire","Francais","Lecture",
     "Lire, comprendre et interpreter un texte litteraire adapte a son age et reagir a sa lecture."),
    ("C3","disciplinaire","Francais","Lecture",
     "Lire et comprendre des textes et des documents (textes, tableaux, graphiques, schemas, diagrammes, images) pour apprendre dans les differentes disciplines."),

    ("C3","disciplinaire","Francais","Ecriture",
     "Ecrire un texte d'une a deux pages, adapte a son destinataire."),
    ("C3","disciplinaire","Francais","Ecriture",
     "Apres revision, obtenir un texte organise et coherent, a la graphie lisible et respectant les regularites orthographiques etudiees au cours du cycle."),

    ("C3","disciplinaire","Francais","Etude de la langue",
     "En redaction de textes dans des contextes varies, maitriser les accords dans le groupe nominal (determinant, nom, adjectif), entre le verbe et son sujet dans des cas simples ainsi que l'accord de l'attribut avec le sujet."),
    ("C3","disciplinaire","Francais","Etude de la langue",
     "Raisonner pour analyser le sens des mots en contexte et en prenant appui sur la morphologie."),
    ("C3","disciplinaire","Francais","Etude de la langue",
     "Etre capable de reperer les principaux constituants d'une phrase simple et complexe."),

    ("C3","disciplinaire","Education musicale",None,
     "Identifier, choisir et mobiliser les techniques vocales et corporelles au service du sens et de l'expression."),
    ("C3","disciplinaire","Education musicale",None,
     "Mettre en lien des caracteristiques musicales d'oeuvres differentes, les nommer et les presenter en lien avec d'autres savoirs construits par les enseignements."),
    ("C3","disciplinaire","Education musicale",None,
     "Explorer les sons de la voix, de l'environnement immediat et de la nature, imaginer des utilisations musicales, creer des organisations dans le temps d'un ensemble de sons selectionnes."),
    ("C3","disciplinaire","Education musicale",None,
     "Developper sa sensibilite, son esprit critique et s'enrichir de la diversite des gouts personnels et des esthetiques."),

    ("C3","disciplinaire","Histoire des arts",None,
     "Decrire une oeuvre en identifiant ses principales caracteristiques techniques et formelles a l'aide d'un lexique simple et adapte."),
    ("C3","disciplinaire","Histoire des arts",None,
     "Emettre une proposition argumentee, fondee sur quelques grandes caracteristiques d'une oeuvre, pour situer celle-ci dans une periode et une aire geographique, au risque de l'erreur."),
    ("C3","disciplinaire","Histoire des arts",None,
     "Exprimer un ressenti et un avis devant une oeuvre, etayes a l'aide d'une premiere analyse."),
    ("C3","disciplinaire","Histoire des arts",None,
     "Se reperer dans un musee ou un centre d'art, adapter son comportement au lieu et identifier la fonction de ses principaux acteurs."),
    ("C3","disciplinaire","Histoire des arts",None,
     "Identifier la marque des arts du passe et du present dans son environnement."),

    ("C3","disciplinaire","EPS","Performance",
     "Realiser des efforts et enchainer plusieurs actions motrices dans differentes familles pour aller plus vite, plus longtemps, plus haut, plus loin."),
    ("C3","disciplinaire","EPS","Performance",
     "Combiner une course, un saut, un lancer pour faire la meilleure performance cumulee."),
    ("C3","disciplinaire","EPS","Performance",
     "Mesurer et quantifier les performances, les enregistrer, les comparer, les classer, les traduire en representations graphiques."),
    ("C3","disciplinaire","EPS","Performance",
     "Assumer les roles de chronometreur et d'observateur."),
    ("C3","disciplinaire","EPS","Environnements varies",
     "Realiser, seul ou a plusieurs, un parcours dans plusieurs environnements inhabituels, en milieu naturel amenage ou artificiel."),
    ("C3","disciplinaire","EPS","Environnements varies",
     "Connaitre et respecter les regles de securite qui s'appliquent a chaque environnement."),
    ("C3","disciplinaire","EPS","Environnements varies",
     "Identifier la personne responsable a alerter ou la procedure en cas de probleme."),
    ("C3","disciplinaire","EPS","Expression artistique",
     "Realiser en petits groupes deux sequences : une a visee acrobatique destinee a etre jugee, une autre a visee artistique destinee a etre appreciee et a emouvoir."),
    ("C3","disciplinaire","EPS","Expression artistique",
     "Savoir filmer une prestation pour la revoir et la faire evoluer."),
    ("C3","disciplinaire","EPS","Expression artistique",
     "Respecter les prestations des autres et accepter de se produire devant les autres."),
    ("C3","disciplinaire","EPS","Affrontement",
     "S'organiser tactiquement pour gagner le duel ou le match en identifiant les situations favorables de marque."),
    ("C3","disciplinaire","EPS","Affrontement",
     "Maintenir un engagement moteur efficace sur tout le temps de jeu prevu."),
    ("C3","disciplinaire","EPS","Affrontement",
     "Respecter les partenaires, les adversaires et l'arbitre."),
    ("C3","disciplinaire","EPS","Affrontement",
     "Assurer differents roles sociaux (joueur, arbitre, observateur) inherents a l'activite et a l'organisation de la classe."),
    ("C3","disciplinaire","EPS","Affrontement",
     "Accepter le resultat de la rencontre et etre capable de le commenter."),

    ("C3","disciplinaire","EMC","Respecter autrui",
     "Respecter autrui : accepter et respecter les differences dans son rapport a l'alterite ; avoir conscience de sa responsabilite individuelle ; adopter une attitude et un langage adaptes dans le rapport aux autres ; tenir compte du point de vue des autres."),
    ("C3","disciplinaire","EMC","Respecter autrui",
     "Partager et reguler des emotions, des sentiments dans des situations et a propos d'objets diversifies, mobiliser le vocabulaire adapte a leur expression."),
    ("C3","disciplinaire","EMC","Valeurs de la Republique",
     "Comprendre les notions de droits, de devoirs et de regles, pour les appliquer et les accepter."),
    ("C3","disciplinaire","EMC","Valeurs de la Republique",
     "Connaitre les valeurs, les principes et les symboles de la Republique francaise, de l'Union europeenne et des societes democratiques."),
    ("C3","disciplinaire","EMC","Valeurs de la Republique",
     "Identifier et connaitre les cadres d'une societe democratique."),
    ("C3","disciplinaire","EMC","Culture civique",
     "Se positionner comme membre de la collectivite."),
    ("C3","disciplinaire","EMC","Culture civique",
     "Prendre en charge des aspects de la vie collective et de l'environnement et developper une conscience civique, y compris dans sa dimension ecologique."),
    ("C3","disciplinaire","EMC","Culture civique",
     "Exercer une aptitude a la reflexion critique pour construire son jugement."),
    ("C3","disciplinaire","EMC","Culture civique",
     "Ecouter autrui et justifier un point de vue au cours d'une conversation, d'un debat ou d'un dialogue."),

    ("C3","disciplinaire","Arts plastiques",None,
     "Realiser des productions plastiques en deux et trois dimensions en mobilisant des outils, des materiaux et des gestes varies au service d'une intention."),
    ("C3","disciplinaire","Arts plastiques",None,
     "Justifier ses choix plastiques et rendre compte, a l'oral ou a l'ecrit, du cheminement qui conduit de l'intention a la realisation."),
    ("C3","disciplinaire","Arts plastiques",None,
     "Decrire et interroger ses propres productions, celles de ses pairs et des oeuvres d'artistes a l'aide d'un vocabulaire specifique adapte."),
    ("C3","disciplinaire","Arts plastiques",None,
     "Identifier quelques caracteristiques (techniques, formelles, culturelles) qui inscrivent une oeuvre dans une aire geographique ou un temps historique."),
    ("C3","disciplinaire","Arts plastiques",None,
     "Mettre en oeuvre un projet artistique individuel ou collectif en prenant en compte les conditions de presentation de la production."),

    ("C3","disciplinaire","Histoire-Geographie","Competences transversales",
     "Se reperer dans le temps en situant des evenements et des periodes sur une frise chronologique, en utilisant un vocabulaire approprie (anteriorite, simultaneite, duree, rupture)."),
    ("C3","disciplinaire","Histoire-Geographie","Competences transversales",
     "Se reperer dans l'espace en localisant et decrivant des lieux et des territoires a differentes echelles a l'aide de cartes et de planispheres."),
    ("C3","disciplinaire","Histoire-Geographie","Competences transversales",
     "Extraire des informations pertinentes d'un document (texte, image, carte, graphique) et identifier la nature et le point de vue de ce document."),
    ("C3","disciplinaire","Histoire-Geographie","Competences transversales",
     "Raconter ou decrire un fait historique, un espace ou un phenomene geographique en utilisant un lexique disciplinaire approprie."),
    ("C3","disciplinaire","Histoire-Geographie","Competences transversales",
     "Realiser ou completer des productions graphiques (croquis, frise, carte simple)."),
    ("C3","disciplinaire","Histoire-Geographie","Histoire",
     "Identifier les grandes periodes de l'histoire etudiees (Prehistoire, Antiquite, Moyen Age, Temps modernes, periode contemporaine) et les situer dans le temps."),
    ("C3","disciplinaire","Histoire-Geographie","Histoire",
     "Decrire quelques caracteristiques d'une societe a une epoque donnee (modes de vie, organisation sociale, pouvoirs, croyances) en s'appuyant sur des exemples concrets."),
    ("C3","disciplinaire","Histoire-Geographie","Histoire",
     "Identifier quelques grandes ruptures historiques et quelques figures ou evenements marquants du passe."),
    ("C3","disciplinaire","Histoire-Geographie","Geographie",
     "Decrire et expliquer comment des groupes humains habitent un espace (ville, campagne, espace a contraintes) en identifiant les principales fonctions de cet espace."),
    ("C3","disciplinaire","Histoire-Geographie","Geographie",
     "Identifier quelques grandes inegalites entre espaces et en expliquer simplement les causes."),
    ("C3","disciplinaire","Histoire-Geographie","Geographie",
     "Reconnaitre des paysages varies et les relier a leurs caracteristiques geographiques et humaines."),

    ("C3","disciplinaire","Sciences et technologie","La matiere",
     "Decrire un echantillon de matiere a l'aide du vocabulaire scientifique et des grandeurs physiques : masse, volume."),
    ("C3","disciplinaire","Sciences et technologie","La matiere",
     "Caracteriser la diversite de la matiere et de ses transformations a l'echelle macroscopique."),
    ("C3","disciplinaire","Sciences et technologie","La matiere",
     "Utiliser les proprietes physiques des materiaux pour les classer, notamment a des fins de tri."),
    ("C3","disciplinaire","Sciences et technologie","Le mouvement",
     "Decrire un mouvement en precisisant le point de vue (referentiel)."),
    ("C3","disciplinaire","Sciences et technologie","Le mouvement",
     "Caracteriser un mouvement par des mesures."),
    ("C3","disciplinaire","Sciences et technologie","Energie",
     "Identifier les formes d'energie mises en jeu dans un dispositif de conversion d'energie."),
    ("C3","disciplinaire","Sciences et technologie","Energie",
     "Rechercher et exploiter des informations relatives aux ressources en energie et a leur utilisation en exercant son esprit critique."),
    ("C3","disciplinaire","Sciences et technologie","Signal et information",
     "Interpreter la formation d'ombres, en particulier dans le contexte du systeme Soleil-Terre-Lune."),
    ("C3","disciplinaire","Sciences et technologie","Signal et information",
     "Mettre en oeuvre des circuits electriques a une boucle en respectant des consignes de securite."),
    ("C3","disciplinaire","Sciences et technologie","Signal et information",
     "Identifier des signaux de natures differentes et citer des applications dans lesquelles un signal permet de transmettre une information."),
    ("C3","disciplinaire","Sciences et technologie","Biodiversite et classification",
     "Caracteriser la richesse, l'unite et la diversite actuelle et passee du vivant."),
    ("C3","disciplinaire","Sciences et technologie","Biodiversite et classification",
     "Classer les organismes et etablir les liens de parente."),
    ("C3","disciplinaire","Sciences et technologie","Alimentation humaine",
     "Expliquer le role des aliments pour le fonctionnement de l'organisme."),
    ("C3","disciplinaire","Sciences et technologie","Alimentation humaine",
     "Identifier les principes des technologies mises en oeuvre pour transformer et conserver les aliments."),
    ("C3","disciplinaire","Sciences et technologie","Cycle de vie et reproduction",
     "Decrire le cycle de vie d'une plante a fleurs et celui d'un animal."),
    ("C3","disciplinaire","Sciences et technologie","Cycle de vie et reproduction",
     "Decrire les changements pubertaires chez les etres humains associes a la capacite de se reproduire."),
    ("C3","disciplinaire","Sciences et technologie","Cycle de vie et reproduction",
     "Identifier la dimension biologique de la sexualite humaine et la distinguer de ses autres dimensions (psycho-emotionnelle, juridique et sociale)."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Identifier un besoin exprime par la societe et lui associer des objets techniques permettant d'y repondre."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Distinguer un objet technique d'un objet naturel."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Reperer les evolutions des objets techniques en fonction de leur contexte d'utilisation."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Citer quelques exemples d'objets techniques concus pour repondre a un besoin specifique et ayant ete detournes de leur usage initial."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Distinguer besoins, fonctions techniques et solutions technologiques."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Decrire un objet technique par un schema (representation du fonctionnement de l'objet) et un croquis (ce que l'on observe)."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Decrire et pratiquer la demarche technologique dans le cadre d'un projet."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Participer a un travail collectif."),
    ("C3","disciplinaire","Sciences et technologie","Objets techniques",
     "Identifier les liens entre des choix de conception et leurs effets sur les etapes du cycle de vie d'un objet technique."),
    ("C3","disciplinaire","Sciences et technologie","Programmation",
     "Reperer la chaine d'information et la chaine d'action d'un objet programmable."),
    ("C3","disciplinaire","Sciences et technologie","Programmation",
     "Programmer un objet technique pour obtenir un comportement attendu."),
    ("C3","disciplinaire","Sciences et technologie","La Terre et ses activites",
     "Identifier l'activite de la planete Terre et ses consequences."),
    ("C3","disciplinaire","Sciences et technologie","La Terre et ses activites",
     "Decrire les conditions de la vie terrestre."),
    ("C3","disciplinaire","Sciences et technologie","La Terre et ses activites",
     "Differencier la meteorologie du climat."),
    ("C3","disciplinaire","Sciences et technologie","La Terre et ses activites",
     "Construire une argumentation scientifique pour expliquer le rechauffement climatique actuel."),
    ("C3","disciplinaire","Sciences et technologie","Ecosystemes",
     "Decrire un ecosysteme et caracteriser les interactions qui s'y deroulent."),
    ("C3","disciplinaire","Sciences et technologie","Ecosystemes",
     "Mettre en evidence la place et l'interdependance de differents etres vivants dans un reseau trophique."),
    ("C3","disciplinaire","Sciences et technologie","Ecosystemes",
     "Caracteriser les consequences d'une action humaine sur un ecosysteme."),

    ("C3","disciplinaire","Mathematiques","Nombres et calculs",
     "Utiliser et representer les grands nombres entiers, des fractions simples, les nombres decimaux."),
    ("C3","disciplinaire","Mathematiques","Nombres et calculs",
     "Calculer avec des nombres entiers et des nombres decimaux."),
    ("C3","disciplinaire","Mathematiques","Nombres et calculs",
     "Resoudre des problemes en utilisant des fractions simples, les nombres decimaux et le calcul."),
    ("C3","disciplinaire","Mathematiques","Grandeurs et mesures",
     "Comparer, estimer, mesurer des grandeurs geometriques avec des nombres entiers et des nombres decimaux : longueur (perimetre), aire, volume, angle."),
    ("C3","disciplinaire","Mathematiques","Grandeurs et mesures",
     "Utiliser le lexique, les unites, les instruments de mesures specifiques de ces grandeurs."),
    ("C3","disciplinaire","Mathematiques","Grandeurs et mesures",
     "Resoudre des problemes impliquant des grandeurs (geometriques, physiques, economiques) en utilisant des nombres entiers et des nombres decimaux."),
    ("C3","disciplinaire","Mathematiques","Espace et geometrie",
     "(Se) reperer et (se) deplacer dans l'espace en utilisant ou en elaborant des representations."),
    ("C3","disciplinaire","Mathematiques","Espace et geometrie",
     "Reconnaitre, nommer, decrire, reproduire, representer, construire des figures et solides usuels."),
    ("C3","disciplinaire","Mathematiques","Espace et geometrie",
     "Reconnaitre et utiliser quelques relations geometriques (notions d'alignement, d'appartenance, de perpendicularite, de parallelisme, d'egalite de longueurs, d'egalite d'angle, de distance entre deux points, de symetrie, d'agrandissement et de reduction)."),
]


def main():
    print("=" * 60)
    print("IMPORT ATTENDUS V2 -> SQLITE")
    print("=" * 60)

    if not DB_PATH.exists():
        print(f"ERREUR : Base SQLite introuvable : {DB_PATH}")
        print("   Lancez d'abord create_schema.py")
        return

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")

    # Verifier la colonne type
    cols = [r[1] for r in conn.execute("PRAGMA table_info(attendu_scolaire)").fetchall()]
    if "type" not in cols:
        print("ERREUR : colonne 'type' absente. Lancez d'abord migration_ajout_type_attendu.py")
        conn.close()
        return

    cycles = conn.execute("SELECT id, code FROM cycle").fetchall()
    cycle_map = {r[1]: r[0] for r in cycles}
    if not cycle_map:
        print("ERREUR : Aucun cycle en base. Lancez d'abord import_pedagogies.py")
        conn.close()
        return

    print(f"  Cycles trouves : {cycle_map}")
    print(f"  {len(ATTENDUS)} attendus a importer...\n")

    inserted = 0
    skipped = 0

    for (cycle_code, type_val, domaine, sous_domaine, libelle) in ATTENDUS:
        cycle_id = cycle_map.get(cycle_code)
        if not cycle_id:
            print(f"  AVERTISSEMENT : cycle '{cycle_code}' inconnu — ligne ignoree")
            skipped += 1
            continue

        cursor = conn.execute("""
            INSERT OR IGNORE INTO attendu_scolaire (cycle_id, domaine, sous_domaine, libelle, type)
            VALUES (?, ?, ?, ?, ?)
        """, (cycle_id, domaine, sous_domaine, libelle, type_val))

        if cursor.rowcount > 0:
            inserted += 1
        else:
            skipped += 1

    conn.commit()

    # Recap par cycle et type
    for code, cid in sorted(cycle_map.items()):
        for t in ("EDD", "disciplinaire"):
            n = conn.execute(
                "SELECT COUNT(*) FROM attendu_scolaire WHERE cycle_id=? AND type=?",
                (cid, t)
            ).fetchone()[0]
            print(f"  {code} {t} : {n} attendus")

    conn.close()

    print(f"\n  OK : {inserted} insere(s), {skipped} ignore(s) (deja presents)")
    print("=" * 60)
    print("Import termine.")
    print("=" * 60)


if __name__ == "__main__":
    main()
